export interface GenreCategory {
  name: string;
  genres: string[];
}

export const GENRE_CATEGORIES: GenreCategory[] = [
  {
    name: 'Rock & Metal',
    genres: [
      'Acid Rock',
      'Alternative Rock',
      'Art Rock',
      'Atmospheric Black Metal',
      'Avant-garde Metal',
      'Black Metal',
      'Blues Rock',
      'Classic Rock',
      'Comedy Rock',
      'Country Rock',
      'Death Metal',
      'Deathcore',
      'Desert Rock',
      'Doom Metal',
      'Electronic Rock',
      'Experimental Metal',
      'Experimental Rock',
      'Folk Metal',
      'Folk Rock',
      'Funk Metal',
      'Funk Rock',
      'Garage Rock',
      'Glam Rock',
      'Gothic Metal',
      'Gothic Rock',
      'Groove Metal',
      'Grunge',
      'Hard Rock',
      'Heavy Metal',
      'Heavy Metal Trap',
      'Industrial Metal',
      'Industrial Rock',
      'Instrumental Rock',
      'Kawaii Metal',
      'Math Rock',
      'Melodic Death Metal',
      'Melodic Metalcore',
      'Metal',
      'Metalcore',
      'New York Hardcore',
      'Noise Rock',
      'Nu Metal',
      'Oriental Metal',
      'Pagan Metal',
      'Piano Rock',
      'Post-Metal',
      'Post-Rock',
      'Power Metal',
      'Progressive Metal',
      'Progressive Rock',
      'Psychedelic Rock',
      'Punk Rock',
      'Rap Metal',
      'Rap Rock',
      'Rock',
      'Rock and Roll',
      'Rock Opera',
      'Rockabilly',
      'Scandinavian Metal',
      'Skate Rock',
      'Sludge Metal',
      'Southern Rock',
      'Space Rock',
      'Speed Metal',
      'Stadium Rock',
      'Stoner Rock',
      'Surf Rock',
      'Symphonic Black Metal',
      'Symphonic Metal',
      'Symphonic Rock',
      'Thrash Metal',
      'Viking Metal',
      'War Metal',
    ],
  },
  {
    name: 'Electronic & Dance',
    genres: [
      'Acid Jazz',
      'Ambient',
      'Bass House',
      'Brostep',
      'Chillwave',
      'Club',
      'Cyberpunk',
      'Dance',
      'Dance Pop',
      'Dark Ambient',
      'Dark Electro',
      'Deep House',
      'Deep Techno',
      'Downtempo',
      'Drone',
      'Dub',
      'Dub Techno',
      'Dubstep',
      'EDM',
      'Electro',
      'Electro Swing',
      'Electroacoustic',
      'Electronic',
      'Electropop',
      'Eurodance',
      'French House',
      'Future Bass',
      'Future Garage',
      'Future House',
      'Gabber',
      'Glitch',
      'Glitch Hop',
      'Glitch Pop',
      'Goa Trance',
      'Happy Hardcore',
      'Hardstyle',
      'House',
      'Hyperpop',
      'IDM (Intelligent Dance Music)',
      'Industrial',
      'Jungle',
      'Minimal Techno',
      'Moombahton',
      'Neurofunk',
      'Nu Disco',
      'Post-Disco',
      'Post-Dubstep',
      'Progressive House',
      'Psybient',
      'Psychedelic Trance',
      'Rave',
      'Space Disco',
      'Synthwave',
      'Tech House',
      'Techno',
      'Trance',
      'Trip Hop',
      'Tropical House',
      'UK Funky',
      'UK Garage',
      'Vaporwave',
      'Vocal House',
      'Vocal Trance',
      'Witch House',
    ],
  },
  {
    name: 'Jazz & Blues',
    genres: [
      'Bebop',
      'Big Band',
      'Blues',
      'Cool Jazz',
      'Dark Jazz',
      'Delta Blues',
      'Gypsy Jazz',
      'Hard Bop',
      'Jazz',
      'Jazz Fusion',
      'Jazz Rap',
      'Latin Jazz',
      'Modal Jazz',
      'New Orleans Jazz',
      'Nu Jazz',
      'Piano Blues',
      'Piedmont Blues',
      'Post-Bop',
      'Punk Blues',
      'Smooth Jazz',
      'Soul Jazz',
      'Swing',
    ],
  },
  {
    name: 'Hip Hop & Rap',
    genres: [
      'Crunk',
      'Hip Hop',
      'Mumble Rap',
      'Pop Rap',
      'Rap',
      'Trap',
      'UK Drill',
      'West Coast Rap',
    ],
  },
  {
    name: 'Folk & World',
    genres: [
      'Afro-Cuban',
      'Afrobeat',
      'Arabian',
      'Arabian Ornamental',
      'Bangra',
      'Bluegrass',
      'Bolero',
      'Calypso',
      'Carnatic',
      'Celtic',
      'Chalga',
      'Chanson',
      'Country',
      'Country Blues',
      'Fado',
      'Flamenco',
      'Folk',
      'Folk Punk',
      'Forró',
      'Freak Folk',
      'Guajira',
      'Hawaiian',
      'Hindustani',
      'Honky Tonk',
      'Indian Classical',
      'Indie Folk',
      'Irish Folk',
      'Klezmer',
      'Latin',
      'Mambo',
      'Mariachi',
      'Neofolk',
      'Nordic Folk',
      'Outlaw Country',
      'Polka',
      'Psychedelic Folk',
      'Qawwali',
      'Quebecois Traditional',
      'Rai',
      'Ranchera',
      'Reggae',
      'Reggaeton',
      'Roots Reggae',
      'Rumba',
      'Russian Folk',
      'Salsa',
      'Samba',
      'Sea Shanties',
      'Sephardic',
      'Spanish Folk',
      'Sufi Music',
      'Taarab',
      'Tango',
      'Traditional',
      'Traditional Folk',
      'Tribal',
      'Truck Driving Country',
      'Urban Folk',
      'World',
      'World Beat',
      'World Fusion',
      'Zydeco',
    ],
  },
  {
    name: 'Pop & Contemporary',
    genres: [
      'Adult Contemporary',
      'Avant-garde',
      'Bedroom',
      'Broadway',
      'Disco',
      'Disco Funk',
      'Dream Pop',
      'Emo',
      'Europop',
      'Funk',
      'Indie',
      'Indie Pop',
      'Indie Rock',
      'J-pop',
      'K-pop',
      'Latin Pop',
      'Lounge',
      'Motown',
      'Neon Pop',
      'Noise Pop',
      'Pop',
      'Pop Punk',
      'Pop Rock',
      'Power Pop',
      'Psychedelic Pop',
      'R&B',
      'Contemporary R&B',
      'Singer-Songwriter',
      'Soft Rock',
      'Soul',
      'Synth-pop',
      'Thai Pop',
      'Urban Contemporary',
    ],
  },
  {
    name: 'Experimental & Avant-garde',
    genres: [
      'Avant-garde Jazz',
      'Dark Cabaret',
      'Dungeon Synth',
      'Experimental',
      'Harsh Noise',
      'Martial Industrial',
      'Musique Concrète',
      'Noise',
      'No Wave',
      'Power Electronics',
      'Sound Art',
      'Sound Collage',
      'Tape Music',
    ],
  },
  {
    name: 'Classical & Orchestral',
    genres: [
      'Adagio',
      'Allegro',
      'Andante',
      'Chamber Music',
      'Classical Crossover',
      'Contemporary Classical',
      'Modern Classical',
      'Neoclassical',
      'Opera',
      'Operatic Pop',
      'Orchestral',
      'Organum',
      'Partita',
      'Requiem',
      'Rhapsody',
      'Romantic',
      'Schoenberg',
      'Serialism',
      'Sonata',
      'Spectralism',
      'String Quartet',
      'Symphonic',
      'Symphony',
      'Twelve-tone',
    ],
  },
  {
    name: 'Vocal & Choral',
    genres: [
      'Acapella',
      'Barbershop',
      'Beatboxing',
      'Choir',
      'Christmas Carol',
      'Doo Wop',
      'Gregorian Chant',
      'Islamic Call to Prayer',
      'Throat Singing',
      'Vocal',
      'Vocal Jazz',
      'Vocaloid',
    ],
  },
  {
    name: 'Soundtrack & Theme',
    genres: [
      'Audiobook Background',
      'Background',
      'Cinematic',
      'Movie Soundtrack',
      'Score',
      'Spaghetti Western',
      'TV Themes',
      'Video Game Music',
      'Villain Theme',
    ],
  },
];

// Flatten all genres for easy searching
export const ALL_GENRES = GENRE_CATEGORIES.flatMap((category) =>
  category.genres.map((genre) => ({
    genre,
    category: category.name,
  }))
);

// Get all unique genres as a simple array
export const GENRE_LIST = ALL_GENRES.map((item) => item.genre);
